/**
 * This module is the handwritten boundary around generated protocol bindings.
 * Runtime code should prefer these curated exports so regenerated files remain
 * isolated under `src/generated/`.
 */
export type {
  ClientInfo,
  ClientNotification,
  ClientRequest,
  InitializeCapabilities,
  InitializeParams,
  InitializeResponse,
  RequestId,
  ServerNotification,
  ServerRequest,
} from "../generated/stable/index.js";

export type {
  AppInfo,
  AppsListParams,
  AppsListResponse,
  CommandExecParams,
  CommandExecResizeParams,
  CommandExecResizeResponse,
  CommandExecResponse,
  CommandExecTerminateParams,
  CommandExecTerminateResponse,
  CommandExecWriteParams,
  CommandExecWriteResponse,
  FsCopyParams,
  FsCopyResponse,
  FsCreateDirectoryParams,
  FsCreateDirectoryResponse,
  FsGetMetadataParams,
  FsGetMetadataResponse,
  FsReadDirectoryEntry,
  FsReadDirectoryParams,
  FsReadDirectoryResponse,
  FsReadFileParams,
  FsReadFileResponse,
  FsRemoveParams,
  FsRemoveResponse,
  FsWriteFileParams,
  FsWriteFileResponse,
  Model,
  ModelListParams,
  ModelListResponse,
  SkillsListEntry,
  SkillsListParams,
  SkillsListResponse,
  Thread,
  ThreadListParams,
  ThreadListResponse,
  ThreadLoadedListParams,
  ThreadLoadedListResponse,
  ThreadReadParams,
  ThreadReadResponse,
  ThreadResumeParams,
  ThreadResumeResponse,
  ThreadStartParams,
  ThreadStartResponse,
  Turn,
  TurnInterruptParams,
  TurnInterruptResponse,
  TurnStartParams,
  TurnStartResponse,
  TurnSteerParams,
  TurnSteerResponse,
} from "../generated/stable/v2/index.js";
